GO
ALTER DATABASE BasketballLeagueDB SET ALLOW_SNAPSHOT_ISOLATION ON
WAITFOR DELAY '00:00:05'
BEGIN TRAN
UPDATE Team SET TeamName = 'Perform Basket' WHERE TeamID = 3
WAITFOR DELAY '00:00:05'
COMMIT TRAN